### ISSUE TITLE
cobblestone crusher crash when fueling

### ISSUE THREAD

**Issue by Mem4mc** [RebelKeithy/Metallurgy3#32]
When placing coal into crusher with iron ore:

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 3/30/13 10:31 PM
Description: Rendering screen

java.lang.ArithmeticException: / by zero
    at rebelkeithy.mods.metallurgy.machines.crusher.TileEntityCrusher.getBurnTimeRemainingScaled(TileEntityCrusher.java:254)
    at rebelkeithy.mods.metallurgy.machines.crusher.GuiCrusher.func_74185_a(GuiCrusher.java:47)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(SourceFile:83)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1021)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:867)
    at net.minecraft.client.Minecraft.run(Minecraft.java:756)
    at java.lang.Thread.run(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at rebelkeithy.mods.metallurgy.machines.crusher.TileEntityCrusher.getBurnTimeRemainingScaled(TileEntityCrusher.java:254)
    at rebelkeithy.mods.metallurgy.machines.crusher.GuiCrusher.func_74185_a(GuiCrusher.java:47)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(SourceFile:83)

-- Screen render details --
Details:
    Screen name: rebelkeithy.mods.metallurgy.machines.crusher.GuiCrusher
    Mouse location: Scaled: (233, 171). Absolute: (466, 425)
    Screen size: Scaled: (512, 384). Absolute: (1024, 768). Scale factor of 2

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['twagclg'/211, l='MpServer', x=35.30, y=61.62, z=106.05]]
    Chunk stats: MultiplayerChunkCache: 441
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (36,64,240), Chunk: (at 4,4,0 in 2,15; contains blocks 32,0,240 to 47,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 18500 game time, 25349 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 85 total; [EntityZombie['Zombie'/24, l='MpServer', x=-41.50, y=15.00, z=77.50], EntityBat['Bat'/1111, l='MpServer', x=62.75, y=16.10, z=119.25], EntitySpider['Spider'/26, l='MpServer', x=-33.09, y=31.00, z=82.91], EntityBat['Bat'/1110, l='MpServer', x=65.29, y=15.59, z=123.60], EntitySheep['Sheep'/28, l='MpServer', x=-40.50, y=72.00, z=93.50], EntityItem['item.item.bone'/1878, l='MpServer', x=96.16, y=60.13, z=69.19], EntityBat['Bat'/45, l='MpServer', x=-0.49, y=39.07, z=106.68], EntityCreeper['Creeper'/775, l='MpServer', x=57.50, y=17.00, z=103.50], EntitySpider['Spider'/55, l='MpServer', x=28.63, y=36.00, z=90.53], EntitySkeleton['Skeleton'/1146, l='MpServer', x=74.50, y=20.00, z=186.50], EntitySkeleton['Skeleton'/53, l='MpServer', x=2.50, y=75.00, z=116.50], EntityBat['Bat'/52, l='MpServer', x=17.73, y=38.02, z=90.01], EntityBat['Bat'/59, l='MpServer', x=23.25, y=36.10, z=119.44], EntityZombie['Zombie'/58, l='MpServer', x=31.84, y=53.00, z=85.84], EntityCreeper['Creeper'/57, l='MpServer', x=30.00, y=34.00, z=90.63], EntitySkeleton['Skeleton'/56, l='MpServer', x=22.50, y=37.00, z=93.06], EntityZombie['Zombie'/61, l='MpServer', x=30.13, y=34.00, z=118.50], EntityCreeper['Creeper'/60, l='MpServer', x=20.59, y=37.00, z=123.00], EntityCreeper['Creeper'/1136, l='MpServer', x=96.50, y=26.00, z=160.50], EntitySkeleton['Skeleton'/68, l='MpServer', x=31.94, y=47.14, z=124.50], EntityCreeper['Creeper'/65, l='MpServer', x=36.69, y=31.00, z=90.38], EntityZombie['Zombie'/66, l='MpServer', x=36.09, y=32.00, z=89.31], EntitySpider['Spider'/67, l='MpServer', x=40.03, y=32.00, z=96.88], EntitySkeleton['Skeleton'/1290, l='MpServer', x=90.50, y=15.00, z=55.50], EntitySkeleton['Skeleton'/85, l='MpServer', x=51.50, y=63.00, z=134.50], EntitySkeleton['Skeleton'/627, l='MpServer', x=106.50, y=37.00, z=148.50], EntitySkeleton['Skeleton'/1291, l='MpServer', x=91.50, y=15.00, z=56.50], EntitySkeleton['Skeleton'/84, l='MpServer', x=55.16, y=63.00, z=134.25], EntitySkeleton['Skeleton'/1288, l='MpServer', x=88.50, y=15.00, z=57.50], EntitySkeleton['Skeleton'/1289, l='MpServer', x=85.88, y=16.00, z=57.50], EntitySkeleton['Skeleton'/86, l='MpServer', x=51.25, y=62.00, z=137.47], EntitySkeleton['Skeleton'/81, l='MpServer', x=63.25, y=54.00, z=74.28], EntityCreeper['Creeper'/80, l='MpServer', x=57.44, y=49.00, z=76.00], EntityCreeper['Creeper'/83, l='MpServer', x=60.50, y=31.00, z=137.50], EntityCreeper['Creeper'/93, l='MpServer', x=79.09, y=47.00, z=80.31], EntitySkeleton['Skeleton'/92, l='MpServer', x=71.34, y=47.00, z=77.66], EntityZombie['Zombie'/94, l='MpServer', x=74.50, y=28.00, z=148.44], EntitySkeleton['Skeleton'/1042, l='MpServer', x=-25.50, y=28.00, z=139.50], EntitySkeleton['Skeleton'/89, l='MpServer', x=64.56, y=43.00, z=59.94], EntityCreeper['Creeper'/91, l='MpServer', x=64.56, y=42.00, z=67.06], EntityBat['Bat'/1067, l='MpServer', x=-38.47, y=38.00, z=94.50], EntitySkeleton['Skeleton'/2298, l='MpServer', x=-3.50, y=29.00, z=145.50], EntitySkeleton['Skeleton'/2299, l='MpServer', x=-2.50, y=29.00, z=142.50], EntitySpider['Spider'/99, l='MpServer', x=74.06, y=64.00, z=169.84], EntitySkeleton['Skeleton'/2297, l='MpServer', x=-6.50, y=29.00, z=143.50], EntityPig['Pig'/110, l='MpServer', x=94.97, y=63.00, z=158.03], EntityPig['Pig'/111, l='MpServer', x=94.47, y=63.00, z=156.63], EntityBat['Bat'/108, l='MpServer', x=89.52, y=29.00, z=116.80], EntitySlime['Slime'/109, l='MpServer', x=85.37, y=55.00, z=106.31], EntitySkeleton['Skeleton'/1806, l='MpServer', x=76.50, y=24.00, z=91.50], EntitySlime['Slime'/118, l='MpServer', x=88.69, y=66.00, z=183.69], EntityItem['item.item.slimeball'/117, l='MpServer', x=95.22, y=62.13, z=165.88], EntityPig['Pig'/116, l='MpServer', x=94.66, y=63.00, z=160.69], EntityZombie['Zombie'/115, l='MpServer', x=91.50, y=34.00, z=166.50], EntityZombie['Zombie'/114, l='MpServer', x=93.50, y=34.00, z=166.50], EntitySheep['Sheep'/112, l='MpServer', x=84.28, y=63.00, z=153.56], EntityZombie['Zombie'/127, l='MpServer', x=105.50, y=47.00, z=154.50], EntityItem['item.item.dyePowder.black'/121, l='MpServer', x=100.84, y=56.13, z=84.25], EntityBat['Bat'/120, l='MpServer', x=99.75, y=48.10, z=59.72], EntityPig['Pig'/129, l='MpServer', x=96.25, y=63.00, z=158.66], EntityCreeper['Creeper'/128, l='MpServer', x=108.50, y=37.00, z=147.50], EntitySlime['Slime'/131, l='MpServer', x=112.93, y=61.00, z=154.48], EntitySpider['Spider'/130, l='MpServer', x=100.75, y=34.00, z=170.66], EntityZombie['Zombie'/1247, l='MpServer', x=95.50, y=37.00, z=59.50], EntityBat['Bat'/2341, l='MpServer', x=106.31, y=30.00, z=114.53], EntityCreeper['Creeper'/2111, l='MpServer', x=108.31, y=36.00, z=141.31], EntitySkeleton['Skeleton'/2350, l='MpServer', x=108.50, y=15.00, z=51.50], EntityZombie['Zombie'/901, l='MpServer', x=113.50, y=23.00, z=175.50], EntityEnderman['Enderman'/1758, l='MpServer', x=114.50, y=32.00, z=60.56], EntitySkeleton['Skeleton'/1155, l='MpServer', x=71.50, y=15.00, z=123.50], EntitySkeleton['Skeleton'/1154, l='MpServer', x=71.50, y=15.00, z=124.50], EntityCreeper['Creeper'/2112, l='MpServer', x=109.00, y=36.00, z=142.47], EntitySkeleton['Skeleton'/757, l='MpServer', x=63.50, y=32.00, z=136.94], EntityBat['Bat'/236, l='MpServer', x=110.22, y=14.10, z=42.28], EntitySheep['Sheep'/233, l='MpServer', x=22.09, y=71.00, z=37.94], EntitySheep['Sheep'/231, l='MpServer', x=18.50, y=71.00, z=29.50], EntityZombie['Zombie'/2174, l='MpServer', x=93.50, y=36.00, z=62.50], EntitySpider['Spider'/230, l='MpServer', x=7.88, y=72.00, z=42.75], EntityZombie['Zombie'/2173, l='MpServer', x=89.50, y=36.00, z=57.50], EntitySheep['Sheep'/227, l='MpServer', x=9.38, y=72.00, z=30.78], EntityItem['item.item.bone'/493, l='MpServer', x=4.72, y=72.13, z=50.00], EntityBat['Bat'/2417, l='MpServer', x=112.50, y=41.00, z=142.50], EntityBat['Bat'/2416, l='MpServer', x=81.50, y=15.00, z=150.50], EntityItem['item.item.arrow'/491, l='MpServer', x=4.88, y=72.13, z=50.25], EntityClientPlayerMP['twagclg'/211, l='MpServer', x=35.30, y=61.62, z=106.05]]
    Retry entities: 0 total; []
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:441)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2405)
    at net.minecraft.client.Minecraft.run(Minecraft.java:772)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.5.1
    Operating System: Windows XP (x86) version 5.1
    Java Version: 1.7.0_17, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 178132752 bytes (169 MB) / 349765632 bytes (333 MB) up to 962985984 bytes (918 MB)
    JVM Flags: 2 total; -Xms345m -Xmx950m
    AABB Pool Size: 3839 (214984 bytes; 0 MB) allocated, 1228 (68768 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 63
    FML: MCP v7.44 FML v5.1.8.611 Minecraft Forge 7.7.1.611 8 mods loaded, 8 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Ideas [Ideas](Metallurgy 3.0.0.0.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Metallurgy3Core [Metallurgy 3 Core](Metallurgy 3.0.0.0.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Metallurgy3Base [Metallurgy 3 Base](Metallurgy 3.0.0.0.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Metallurgy3Machines [Metallurgy 3 Machines](Metallurgy 3.0.0.0.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Metallurgy3Vanilla [Metallurgy 3 Vanilla](Metallurgy 3.0.0.0.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    LWJGL: 2.4.2
    OpenGL: GeForce 210/PCI/SSE2/3DNOW! GL version 3.3.0, NVIDIA Corporation
    Is Modded: Definitely; Client brand changed to 'forge,fml'
    Type: Client (map_client.txt)
    Texture Pack: Default
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 1078 (60368 bytes; 0 MB) allocated, 662 (37072 bytes; 0 MB) used

Mem

**Comment by BSKCraft** [comment]
I am experiencing this same issue I created a ticket here but it has vanished or did not go through. I have tried with just Forge and Metallurgy installed to see if any other plugins may be the issue and it is not. I still get this. So instead of posting yet another ticket I am just glad to see I am not the only one now having this issue.

**Comment by RebelKeithy** [comment]
Found the problem, in the configs crusher speeds were listed as 6000.0 instead of 6000 this was causing problems, I've fixed the default values of this for next update, but you will need to delete your configs (or at least the crusher and furnace speed values).

**Comment by kingofthesheep** [comment]
Still getting the same error with the up date even after clearing configs, at least for the copper crushers

Edit: would making a new world fix it possibly?

**Comment by BSKCraft** [comment]
No.. I fixed the issue myself even before downloading the new update. Go into your Metallurgy 3 Config and go to machines.. scroll down to Crusher speeds and just remove the .0 from all. Fixed for me. Or also just delete your entire config folder not your main one, the one from Metallurgy only and restart minecraft. I fixed it myself because I edited at what levels the ores will start showing and I did not want to do that over again. After reading what caused the issues I just edited the problem and it fixed. I was able to use them again.
